### ISSUE TITLE
Table data cannot be loaded asynchronously

### ISSUE THREAD

**Issue by emertechie** [alfonsobries/vue-tailwind#90] opened 2020-10-17 09:49 UTC
Pretty much as title says. If `t-table` is bound to a `tableData` array, and that array is populated after the initial rendering of the table, no rows are rendered.

**Comment by alfonsobries** [comment] 2020-10-20 23:12
Its possible to have a reproduction link or a chunk of your code cannot replicate any error

**Comment by alfonsobries** [comment] 2020-10-22 01:45
I'll close this issue for now since cannot reproduce the problem, if you have more info feel free to open the issue again @emertechie

**Closed by alfonsobries** 2020-10-22 01:45 UTC
