### ISSUE TITLE
[Vue warn]: $attrs is readonly., [Vue warn]: $listeners is readonly.

### ISSUE THREAD

**Issue by pantajoe** [alfonsobries/vue-tailwind#94] opened 2020-11-03 16:56 UTC
Hey! First of all, I really enjoy VueTailwind.

However, I encountered an issue when using this library.

I get the warnings `[Vue warn]: $attrs is readonly` and `[Vue warn]: $listeners is readonly.` when using the component `TDatepicker`. I do not know if this is the case with any other VueTailwind component, but I most certainly think so.

When looking at the stack trace, there are 2 different Vue instances. The one in the `node_modules` folder of the package `vue-tailwind` and the one in my direct dependencies.
Those 2 instances are imported from those different locations:

* `./node_modules/vue/dist/vue.esm.js`
* `.node_modules/vue-tailwind/node_modules/vue/dist/vue.esm.js`

This has been identified as the issue for such strange warning messages: https://stackoverflow.com/questions/49585845/attrs-is-readonly-listeners-is-readonly-avoid-mutating-a-prop-directly.

I already setup my webpack config in such a way that when `vue` is referenced during an import, `vue/dist/vue/esm.js` is used instead (by using the option `resolve alias` with `vue$: 'vue/dist/vue.esm.js'`. But that didn't seem to do the trick.

Is it possible not to declare `vue` as a dependency for `vue-tailwind`, such that no internal `node_modules` folder is generated inside the `vue-tailwind` folder when installing it?

**EDIT:**
Okay, the following workaround seems to work with webpack (I have to extend my default webpack like this since i use Rails):

```javascript
// config/webpack/customConfig.js
const path = require('path');

module.exports = {
...,
resolve: {
  alias: {
    vue$: path.resolve(__dirname, '../..', 'node_modules', 'vue/dist/vue.esm.js'),
  },
},
...
};
```

Although this seems kind of odd since the official guide says to stick to this alias definition for vue: `vue$: 'vue/dist/vue.esm.js'`.

**Comment by alfonsobries** [comment] 2020-11-13 22:42
Ok after research for this your solution seems to be the correct one so Ill close this issue for now, feel free to open again if you encounter more problems related to this.

**Closed by alfonsobries** 2020-11-13 22:42 UTC

**Comment by quantumlink** [comment] 2021-02-18 06:07
I also have this issue, but no Rails setup, I tried the above in my `vue.config.js` and still seeing the above errors which appear to be indicating two Vue instances
```
module.exports = {
  configureWebpack: {
    resolve: {
      alias: {
        'vue$': 'vue/dist/vue.runtime.esm.js'
        ```
I've confirmed that alias seems to be active as changing the value to anything wrong indicates it matters.

**Comment by pantajoe** [comment] 2021-02-18 06:15
@quantumlink Hey! Did you really try aliasing to the `vue.runtime` in your *own* node_modules?

Like this: `vue$: path.resolve(__dirname, 'node_modules', 'vue/dist/vue.runtime.esm.js')` by resolving the node_modules path relatively with `__dirname`.

Hope this helps.

**Comment by quantumlink** [comment] 2021-02-18 08:27
I deleted my post after literally getting it to work moments after posting it.
What you wrote there works, I think what I had somehow referenced the global? Either way it seems that works. 
Is this due to something that can be resolved in the plugin in how it shares the vue instance?
